export enum WidgetType {
  SITE = 'SITE',
  DOCUMENT = 'DOCUMENT',
  TEXT_ANSWER = 'TEXT_ANSWER',
  NUMBER = 'NUMBER',
  CHECKBOX = 'CHECKBOX',
  DATE_TIME = 'DATE_TIME',
  MEDIA = 'MEDIA',
  SLIDER = 'SLIDER',
  ANNOTATION = 'ANNOTATION',
  SIGNATURE = 'SIGNATURE',
  LOCATION = 'LOCATION',
  INSTRUCTION = 'INSTRUCTION',
}
